### ISSUE TITLE
Font is hard to read in Firefox PC browser.

### ISSUE THREAD

**Issue by jdelaporte** [edthedev/MyGoal.space#12]
I don't know if the font changed, but it's hard to read on my work computer. 
![mygoalspace1](https://cloud.githubusercontent.com/assets/3790057/9121178/4b5d6bb4-3c46-11e5-8e5a-40c3eca4ed14.png)

**Comment by edthedev** [comment]
Was even worse in IE. Changed the font to something more reasonable. Please re-open if this is still an issue.
