### ISSUE TITLE
Backspace goes back in browser when trying to edit text in editable action field (Goals tab)

### ISSUE THREAD

**Issue by jdelaporte** [edthedev/MyGoal.space#20]
Backspace goes back in browser when trying to edit text in editable action field on the main page, which is the Goals tab. It might work correctly for one backspace action, but holding down Backspace, or tapping it multiple times results in the browser navigating back, rather than removing text.

I suspect this is related to the live-update the page now does. Maybe live update can be delayed until the field is done being edited (Enter key is pressed, or focus moved elsewhere)?

**Comment by edthedev** [comment]
I believe this is resolved. Please re-open if it happens again.
