### ISSUE TITLE
Unscheduled actions appear at top/beginning of list on Goals tab...they'd be more useful at the bottom/end of list

### ISSUE THREAD

**Issue by jdelaporte** [edthedev/MyGoal.space#42]
Unscheduled actions appear at top/beginning of list on Goals tab...they'd be more useful at the bottom/end of list.

**Comment by edthedev** [comment]
Not easily changed, since it would also make the other items sort backwards.

app.py line 461

```
     sql = """select * from action where goal_id = $goal and complete is null and user=$user order by "when";"""
```

null items in when happen to sort to the top in this db engine. I could get fancy with it, but it would slow down this part of the app, which doesn't seem like a good trade-off for this issue.

**Comment by edthedev** [comment]
Huh. Turns out it can be done at the database level after all. This is implemented.
