### ISSUE TITLE
Save new goal (btn-done) needs to be default action for Enter when adding a new goal

### ISSUE THREAD

**Issue by jdelaporte** [edthedev/MyGoal.space#9]
When adding a new goal, the anticipated behaviour (on a PC) is that pressing "Enter" will activate the Save new goal (btn-done) action. On mobile, there is a "next" action instead of "Enter" that works as expected for a little while, moving the cursor to the next field, but it actually gets stuck in the "Strength" text area, inserting new lines rather than moving to the next field.

**Comment by edthedev** [comment]
Confirmed in version 9.0.

**Comment by edthedev** [comment]
Confirmed in latest version.

**Comment by edthedev** [comment]
Fixed.
